INSERT INTO public."PeruDistrict" (name,"provinceId","updatedAt") VALUES
( 'Chachapoyas', 1, NOW()),
( 'Asunción', 1, NOW()),
( 'Balsas', 1, NOW()),
( 'Cheto', 1, NOW()),
( 'Chiliquin', 1, NOW()),
( 'Chuquibamba', 1, NOW()),
( 'Granada', 1, NOW()),
( 'Huancas', 1, NOW()),
( 'La Jalca', 1, NOW()),
( 'Leimebamba', 1, NOW()),
( 'Levanto', 1, NOW()),
( 'Magdalena', 1, NOW()),
( 'Mariscal Castilla', 1, NOW()),
( 'Molinopampa', 1, NOW()),
( 'Montevideo', 1, NOW()),
( 'Olleros', 1, NOW()),
( 'Quinjalca', 1, NOW()),
( 'San Francisco de Daguas', 1, NOW()),
( 'San Isidro de Maino', 1, NOW()),
( 'Soloco', 1, NOW()),
( 'Sonche', 1, NOW()),
( 'Bagua', 2, NOW()),
( 'Aramango', 2, NOW()),
( 'Copallin', 2, NOW()),
( 'El Parco', 2, NOW()),
( 'Imaza', 2, NOW()),
( 'La Peca', 2, NOW()),
( 'Jumbilla', 3, NOW()),
( 'Chisquilla', 3, NOW()),
( 'Churuja', 3, NOW()),
( 'Corosha', 3, NOW()),
( 'Cuispes', 3, NOW()),
( 'Florida', 3, NOW()),
( 'Jazan', 3, NOW()),
( 'Recta', 3, NOW()),
( 'San Carlos', 3, NOW()),
( 'Shipasbamba', 3, NOW()),
( 'Valera', 3, NOW()),
( 'Yambrasbamba', 3, NOW()),
( 'Nieva', 4, NOW()),
( 'El Cenepa', 4, NOW()),
( 'Río Santiago', 4, NOW()),
( 'Lamud', 5, NOW()),
( 'Camporredondo', 5, NOW()),
( 'Cocabamba', 5, NOW()),
( 'Colcamar', 5, NOW()),
( 'Conila', 5, NOW()),
( 'Inguilpata', 5, NOW()),
( 'Longuita', 5, NOW()),
( 'Lonya Chico', 5, NOW()),
( 'Luya', 5, NOW()),
( 'Luya Viejo', 5, NOW()),
( 'María', 5, NOW()),
( 'Ocalli', 5, NOW()),
( 'Ocumal', 5, NOW()),
( 'Pisuquia', 5, NOW()),
( 'Providencia', 5, NOW()),
( 'San Cristóbal', 5, NOW()),
( 'San Francisco de Yeso', 5, NOW()),
( 'San Jerónimo', 5, NOW()),
( 'San Juan de Lopecancha', 5, NOW()),
( 'Santa Catalina', 5, NOW()),
( 'Santo Tomas', 5, NOW()),
( 'Tingo', 5, NOW()),
( 'Trita', 5, NOW()),
( 'San Nicolás', 6, NOW()),
( 'Chirimoto', 6, NOW()),
( 'Cochamal', 6, NOW()),
( 'Huambo', 6, NOW()),
( 'Limabamba', 6, NOW()),
( 'Longar', 6, NOW()),
( 'Mariscal Benavides', 6, NOW()),
( 'Milpuc', 6, NOW()),
( 'Omia', 6, NOW()),
( 'Santa Rosa', 6, NOW()),
( 'Totora', 6, NOW()),
( 'Vista Alegre', 6, NOW()),
( 'Bagua Grande', 7, NOW()),
( 'Cajaruro', 7, NOW()),
( 'Cumba', 7, NOW()),
( 'El Milagro', 7, NOW()),
( 'Jamalca', 7, NOW()),
( 'Lonya Grande', 7, NOW()),
( 'Yamon', 7, NOW()),
( 'Huaraz', 8, NOW()),
( 'Cochabamba', 8, NOW()),
( 'Colcabamba', 8, NOW()),
( 'Huanchay', 8, NOW()),
( 'Independencia', 8, NOW()),
( 'Jangas', 8, NOW()),
( 'La Libertad', 8, NOW()),
( 'Olleros', 8, NOW()),
( 'Pampas Grande', 8, NOW()),
( 'Pariacoto', 8, NOW()),
( 'Pira', 8, NOW()),
( 'Tarica', 8, NOW()),
( 'Aija', 9, NOW()),
( 'Coris', 9, NOW()),
( 'Huacllan', 9, NOW()),
( 'La Merced', 9, NOW()),
( 'Succha', 9, NOW()),
( 'Llamellin', 10, NOW()),
( 'Aczo', 10, NOW()),
( 'Chaccho', 10, NOW()),
( 'Chingas', 10, NOW()),
( 'Mirgas', 10, NOW()),
( 'San Juan de Rontoy', 10, NOW()),
( 'Chacas', 11, NOW()),
( 'Acochaca', 11, NOW()),
( 'Chiquian', 12, NOW()),
( 'Abelardo Pardo Lezameta', 12, NOW()),
( 'Antonio Raymondi', 12, NOW()),
( 'Aquia', 12, NOW()),
( 'Cajacay', 12, NOW()),
( 'Canis', 12, NOW()),
( 'Colquioc', 12, NOW()),
( 'Huallanca', 12, NOW()),
( 'Huasta', 12, NOW()),
( 'Huayllacayan', 12, NOW()),
( 'La Primavera', 12, NOW()),
( 'Mangas', 12, NOW()),
( 'Pacllon', 12, NOW()),
( 'San Miguel de Corpanqui', 12, NOW()),
( 'Ticllos', 12, NOW()),
( 'Carhuaz', 13, NOW()),
( 'Acopampa', 13, NOW()),
( 'Amashca', 13, NOW()),
( 'Anta', 13, NOW()),
( 'Ataquero', 13, NOW()),
( 'Marcara', 13, NOW()),
( 'Pariahuanca', 13, NOW()),
( 'San Miguel de Aco', 13, NOW()),
( 'Shilla', 13, NOW()),
( 'Tinco', 13, NOW()),
( 'Yungar', 13, NOW()),
( 'San Luis', 14, NOW()),
( 'San Nicolás', 14, NOW()),
( 'Yauya', 14, NOW()),
( 'Casma', 15, NOW()),
( 'Buena Vista Alta', 15, NOW()),
( 'Comandante Noel', 15, NOW()),
( 'Yautan', 15, NOW()),
( 'Corongo', 16, NOW()),
( 'Aco', 16, NOW()),
( 'Bambas', 16, NOW()),
( 'Cusca', 16, NOW()),
( 'La Pampa', 16, NOW()),
( 'Yanac', 16, NOW()),
( 'Yupan', 16, NOW()),
( 'Huari', 17, NOW()),
( 'Anra', 17, NOW()),
( 'Cajay', 17, NOW()),
( 'Chavin de Huantar', 17, NOW()),
( 'Huacachi', 17, NOW()),
( 'Huacchis', 17, NOW()),
( 'Huachis', 17, NOW()),
( 'Huantar', 17, NOW()),
( 'Masin', 17, NOW()),
( 'Paucas', 17, NOW()),
( 'Ponto', 17, NOW()),
( 'Rahuapampa', 17, NOW()),
( 'Rapayan', 17, NOW()),
( 'San Marcos', 17, NOW()),
( 'San Pedro de Chana', 17, NOW()),
( 'Uco', 17, NOW()),
( 'Huarmey', 18, NOW()),
( 'Cochapeti', 18, NOW()),
( 'Culebras', 18, NOW()),
( 'Huayan', 18, NOW()),
( 'Malvas', 18, NOW()),
( 'Caraz', 19, NOW()),
( 'Huallanca', 19, NOW()),
( 'Huata', 19, NOW()),
( 'Huaylas', 19, NOW()),
( 'Mato', 19, NOW()),
( 'Pamparomas', 19, NOW()),
( 'Pueblo Libre', 19, NOW()),
( 'Santa Cruz', 19, NOW()),
( 'Santo Toribio', 19, NOW()),
( 'Yuracmarca', 19, NOW()),
( 'Piscobamba', 20, NOW()),
( 'Casca', 20, NOW()),
( 'Eleazar Guzmán Barron', 20, NOW()),
( 'Fidel Olivas Escudero', 20, NOW()),
( 'Llama', 20, NOW()),
( 'Llumpa', 20, NOW()),
( 'Lucma', 20, NOW()),
( 'Musga', 20, NOW()),
( 'Ocros', 21, NOW()),
( 'Acas', 21, NOW()),
( 'Cajamarquilla', 21, NOW()),
( 'Carhuapampa', 21, NOW()),
( 'Cochas', 21, NOW()),
( 'Congas', 21, NOW()),
( 'Llipa', 21, NOW()),
( 'San Cristóbal de Rajan', 21, NOW()),
( 'San Pedro', 21, NOW()),
( 'Santiago de Chilcas', 21, NOW()),
( 'Cabana', 22, NOW()),
( 'Bolognesi', 22, NOW()),
( 'Conchucos', 22, NOW()),
( 'Huacaschuque', 22, NOW()),
( 'Huandoval', 22, NOW()),
( 'Lacabamba', 22, NOW()),
( 'Llapo', 22, NOW()),
( 'Pallasca', 22, NOW()),
( 'Pampas', 22, NOW()),
( 'Santa Rosa', 22, NOW()),
( 'Tauca', 22, NOW()),
( 'Pomabamba', 23, NOW()),
( 'Huayllan', 23, NOW()),
( 'Parobamba', 23, NOW()),
( 'Quinuabamba', 23, NOW()),
( 'Recuay', 24, NOW()),
( 'Catac', 24, NOW()),
( 'Cotaparaco', 24, NOW()),
( 'Huayllapampa', 24, NOW()),
( 'Llacllin', 24, NOW()),
( 'Marca', 24, NOW()),
( 'Pampas Chico', 24, NOW()),
( 'Pararin', 24, NOW()),
( 'Tapacocha', 24, NOW()),
( 'Ticapampa', 24, NOW()),
( 'Chimbote', 25, NOW()),
( 'Cáceres del Perú', 25, NOW()),
( 'Coishco', 25, NOW()),
( 'Macate', 25, NOW()),
( 'Moro', 25, NOW()),
( 'Nepeña', 25, NOW()),
( 'Samanco', 25, NOW()),
( 'Santa', 25, NOW()),
( 'Nuevo Chimbote', 25, NOW()),
( 'Sihuas', 26, NOW()),
( 'Acobamba', 26, NOW()),
( 'Alfonso Ugarte', 26, NOW()),
( 'Cashapampa', 26, NOW()),
( 'Chingalpo', 26, NOW()),
( 'Huayllabamba', 26, NOW()),
( 'Quiches', 26, NOW()),
( 'Ragash', 26, NOW()),
( 'San Juan', 26, NOW()),
( 'Sicsibamba', 26, NOW()),
( 'Yungay', 27, NOW()),
( 'Cascapara', 27, NOW()),
( 'Mancos', 27, NOW()),
( 'Matacoto', 27, NOW()),
( 'Quillo', 27, NOW()),
( 'Ranrahirca', 27, NOW()),
( 'Shupluy', 27, NOW()),
( 'Yanama', 27, NOW()),
( 'Abancay',28, NOW()),
( 'Chacoche',28, NOW()),
( 'Circa',28, NOW()),
( 'Curahuasi',28, NOW()),
( 'Huanipaca',28, NOW()),
( 'Lambrama',28, NOW()),
( 'Pichirhua',28, NOW()),
( 'San Pedro de Cachora',28, NOW()),
( 'Tamburco',28, NOW()),
( 'Andahuaylas', 29, NOW()),
( 'Andarapa', 29, NOW()),
( 'Chiara', 29, NOW()),
( 'Huancarama', 29, NOW()),
( 'Huancaray', 29, NOW()),
( 'Huayana', 29, NOW()),
( 'Kishuara', 29, NOW()),
( 'Pacobamba', 29, NOW()),
( 'Pacucha', 29, NOW()),
( 'Pampachiri', 29, NOW()),
( 'Pomacocha', 29, NOW()),
( 'San Antonio de Cachi', 29, NOW()),
( 'San Jerónimo', 29, NOW()),
( 'San Miguel de Chaccrampa', 29, NOW()),
( 'Santa María de Chicmo', 29, NOW()),
( 'Talavera', 29, NOW()),
( 'Tumay Huaraca', 29, NOW()),
( 'Turpo', 29, NOW()),
( 'Kaquiabamba', 29, NOW()),
( 'José María Arguedas', 29, NOW()),
( 'Antabamba', 30, NOW()),
( 'El Oro', 30, NOW()),
( 'Huaquirca', 30, NOW()),
( 'Juan Espinoza Medrano', 30, NOW()),
( 'Oropesa', 30, NOW()),
( 'Pachaconas', 30, NOW()),
( 'Sabaino', 30, NOW()),
( 'Chalhuanca', 31, NOW()),
( 'Capaya', 31, NOW()),
( 'Caraybamba', 31, NOW()),
( 'Chapimarca', 31, NOW()),
( 'Colcabamba', 31, NOW()),
( 'Cotaruse', 31, NOW()),
( 'Ihuayllo', 31, NOW()),
( 'Justo Apu Sahuaraura', 31, NOW()),
( 'Lucre', 31, NOW()),
( 'Pocohuanca', 31, NOW()),
( 'San Juan de Chacña', 31, NOW()),
( 'Sañayca', 31, NOW()),
( 'Soraya', 31, NOW()),
( 'Tapairihua', 31, NOW()),
( 'Tintay', 31, NOW()),
( 'Toraya', 31, NOW()),
( 'Yanaca', 31, NOW()),
( 'Tambobamba', 32, NOW()),
( 'Cotabambas', 32, NOW()),
( 'Coyllurqui', 32, NOW()),
( 'Haquira', 32, NOW()),
( 'Mara', 32, NOW()),
( 'Challhuahuacho', 32, NOW()),
( 'Chincheros', 33, NOW()),
( 'Anco_Huallo', 33, NOW()),
( 'Cocharcas', 33, NOW()),
( 'Huaccana', 33, NOW()),
( 'Ocobamba', 33, NOW()),
( 'Ongoy', 33, NOW()),
( 'Uranmarca', 33, NOW()),
( 'Ranracancha', 33, NOW()),
( 'Rocchacc', 33, NOW()),
( 'El Porvenir', 33, NOW()),
( 'Los Chankas', 33, NOW()),
( 'Chuquibambilla', 34, NOW()),
( 'Curpahuasi', 34, NOW()),
( 'Gamarra', 34, NOW()),
( 'Huayllati', 34, NOW()),
( 'Mamara', 34, NOW()),
( 'Micaela Bastidas', 34, NOW()),
( 'Pataypampa', 34, NOW()),
( 'Progreso', 34, NOW()),
( 'San Antonio', 34, NOW()),
( 'Santa Rosa', 34, NOW()),
( 'Turpay', 34, NOW()),
( 'Vilcabamba', 34, NOW()),
( 'Virundo', 34, NOW()),
( 'Curasco', 34, NOW()),
( 'Arequipa', 35, NOW()),
( 'Alto Selva Alegre', 35, NOW()),
( 'Cayma', 35, NOW()),
( 'Cerro Colorado', 35, NOW()),
( 'Characato', 35, NOW()),
( 'Chiguata', 35, NOW()),
( 'Jacobo Hunter', 35, NOW()),
( 'La Joya', 35, NOW()),
( 'Mariano Melgar', 35, NOW()),
( 'Miraflores', 35, NOW()),
( 'Mollebaya', 35, NOW()),
( 'Paucarpata', 35, NOW()),
( 'Pocsi', 35, NOW()),
( 'Polobaya', 35, NOW()),
( 'Quequeña', 35, NOW()),
( 'Sabandia', 35, NOW()),
( 'Sachaca', 35, NOW()),
( 'San Juan de Siguas', 35, NOW()),
( 'San Juan de Tarucani', 35, NOW()),
( 'Santa Isabel de Siguas', 35, NOW()),
( 'Santa Rita de Siguas', 35, NOW()),
( 'Socabaya', 35, NOW()),
( 'Tiabaya', 35, NOW()),
( 'Uchumayo', 35, NOW()),
( 'Vitor', 35, NOW()),
( 'Yanahuara', 35, NOW()),
( 'Yarabamba', 35, NOW()),
( 'Yura', 35, NOW()),
( 'José Luis Bustamante Y Rivero', 36, NOW()),
( 'Camaná', 36, NOW()),
( 'José María Quimper', 36, NOW()),
( 'Mariano Nicolás Valcárcel', 36, NOW()),
( 'Mariscal Cáceres', 36, NOW()),
( 'Nicolás de Pierola', 36, NOW()),
( 'Ocoña', 36, NOW()),
( 'Quilca', 36, NOW()),
( 'Samuel Pastor', 36, NOW()),
( 'Caravelí', 37, NOW()),
( 'Acarí', 37, NOW()),
( 'Atico', 37, NOW()),
( 'Atiquipa', 37, NOW()),
( 'Bella Unión', 37, NOW()),
( 'Cahuacho', 37, NOW()),
( 'Chala', 37, NOW()),
( 'Chaparra', 37, NOW()),
( 'Huanuhuanu', 37, NOW()),
( 'Jaqui', 37, NOW()),
( 'Lomas', 37, NOW()),
( 'Quicacha', 37, NOW()),
( 'Yauca', 37, NOW()),
( 'Aplao', 38, NOW()),
( 'Andagua', 38, NOW()),
( 'Ayo', 38, NOW()),
( 'Chachas', 38, NOW()),
( 'Chilcaymarca', 38, NOW()),
( 'Choco', 38, NOW()),
( 'Huancarqui', 38, NOW()),
( 'Machaguay', 38, NOW()),
( 'Orcopampa', 38, NOW()),
( 'Pampacolca', 38, NOW()),
( 'Tipan', 38, NOW()),
( 'Uñon', 38, NOW()),
( 'Uraca', 38, NOW()),
( 'Viraco', 38, NOW()),
( 'Chivay', 39, NOW()),
( 'Achoma', 39, NOW()),
( 'Cabanaconde', 39, NOW()),
( 'Callalli', 39, NOW()),
( 'Caylloma', 39, NOW()),
( 'Coporaque', 39, NOW()),
( 'Huambo', 39, NOW()),
( 'Huanca', 39, NOW()),
( 'Ichupampa', 39, NOW()),
( 'Lari', 39, NOW()),
( 'Lluta', 39, NOW()),
( 'Maca', 39, NOW()),
( 'Madrigal', 39, NOW()),
( 'San Antonio de Chuca', 39, NOW()),
( 'Sibayo', 39, NOW()),
( 'Tapay', 39, NOW()),
( 'Tisco', 39, NOW()),
( 'Tuti', 39, NOW()),
( 'Yanque', 39, NOW()),
( 'Majes', 39, NOW()),
( 'Chuquibamba', 40, NOW()),
( 'Andaray', 40, NOW()),
( 'Cayarani', 40, NOW()),
( 'Chichas', 40, NOW()),
( 'Iray', 40, NOW()),
( 'Río Grande', 40, NOW()),
( 'Salamanca', 40, NOW()),
( 'Yanaquihua', 40, NOW()),
( 'Mollendo', 41, NOW()),
( 'Cocachacra', 41, NOW()),
( 'Dean Valdivia', 41, NOW()),
( 'Islay', 41, NOW()),
( 'Mejia', 41, NOW()),
( 'Punta de Bombón', 41, NOW()),
( 'Cotahuasi', 42, NOW()),
( 'Alca', 42, NOW()),
( 'Charcana', 42, NOW()),
( 'Huaynacotas', 42, NOW()),
( 'Pampamarca', 42, NOW()),
( 'Puyca', 42, NOW()),
( 'Quechualla', 42, NOW()),
( 'Sayla', 42, NOW()),
( 'Tauria', 42, NOW()),
( 'Tomepampa', 42, NOW()),
( 'Toro', 42, NOW()),
( 'Ayacucho', 43, NOW()),
( 'Acocro', 43, NOW()),
( 'Acos Vinchos', 43, NOW()),
( 'Carmen Alto', 43, NOW()),
( 'Chiara', 43, NOW()),
( 'Ocros', 43, NOW()),
( 'Pacaycasa', 43, NOW()),
( 'Quinua', 43, NOW()),
( 'San José de Ticllas', 43, NOW()),
( 'San Juan Bautista', 43, NOW()),
( 'Santiago de Pischa', 43, NOW()),
( 'Socos', 43, NOW()),
( 'Tambillo', 43, NOW()),
( 'Vinchos', 43, NOW()),
( 'Jesús Nazareno', 43, NOW()),
( 'Andrés Avelino Cáceres Dorregaray', 43, NOW()),
( 'Cangallo', 44, NOW()),
( 'Chuschi', 44, NOW()),
( 'Los Morochucos', 44, NOW()),
( 'María Parado de Bellido', 44, NOW()),
( 'Paras', 44, NOW()),
( 'Totos', 44, NOW()),
( 'Sancos', 45, NOW()),
( 'Carapo', 45, NOW()),
( 'Sacsamarca', 45, NOW()),
( 'Santiago de Lucanamarca', 45, NOW()),
( 'Huanta', 46, NOW()),
( 'Ayahuanco', 46, NOW()),
( 'Huamanguilla', 46, NOW()),
( 'Iguain', 46, NOW()),
( 'Luricocha', 46, NOW()),
( 'Santillana', 46, NOW()),
( 'Sivia', 46, NOW()),
( 'Llochegua', 46, NOW()),
( 'Canayre', 46, NOW()),
( 'Uchuraccay', 46, NOW()),
( 'Pucacolpa', 46, NOW()),
( 'Chaca', 46, NOW()),
( 'San Miguel', 47, NOW()),
( 'Anco', 47, NOW()),
( 'Ayna', 47, NOW()),
( 'Chilcas', 47, NOW()),
( 'Chungui', 47, NOW()),
( 'Luis Carranza', 47, NOW()),
( 'Santa Rosa', 47, NOW()),
( 'Tambo', 47, NOW()),
( 'Samugari', 47, NOW()),
( 'Anchihuay', 47, NOW()),
( 'Oronccoy', 47, NOW()),
( 'Puquio', 48, NOW()),
( 'Aucara', 48, NOW()),
( 'Cabana', 48, NOW()),
( 'Carmen Salcedo', 48, NOW()),
( 'Chaviña', 48, NOW()),
( 'Chipao', 48, NOW()),
( 'Huac-Huas', 48, NOW()),
( 'Laramate', 48, NOW()),
( 'Leoncio Prado', 48, NOW()),
( 'Llauta', 48, NOW()),
( 'Lucanas', 48, NOW()),
( 'Ocaña', 48, NOW()),
( 'Otoca', 48, NOW()),
( 'Saisa', 48, NOW()),
( 'San Cristóbal', 48, NOW()),
( 'San Juan', 48, NOW()),
( 'San Pedro', 48, NOW()),
( 'San Pedro de Palco', 48, NOW()),
( 'Sancos', 48, NOW()),
( 'Santa Ana de Huaycahuacho', 48, NOW()),
( 'Santa Lucia', 48, NOW()),
( 'Coracora', 49, NOW()),
( 'Chumpi', 49, NOW()),
( 'Coronel Castañeda', 49, NOW()),
( 'Pacapausa', 49, NOW()),
( 'Pullo', 49, NOW()),
( 'Puyusca', 49, NOW()),
( 'San Francisco de Ravacayco', 49, NOW()),
( 'Upahuacho', 49, NOW()),
( 'Pausa', 50, NOW()),
( 'Colta', 50, NOW()),
( 'Corculla', 50, NOW()),
( 'Lampa', 50, NOW()),
( 'Marcabamba', 50, NOW()),
( 'Oyolo', 50, NOW()),
( 'Pararca', 50, NOW()),
( 'San Javier de Alpabamba', 50, NOW()),
( 'San José de Ushua', 50, NOW()),
( 'Sara Sara', 50, NOW()),
( 'Querobamba', 51, NOW()),
( 'Belén', 51, NOW()),
( 'Chalcos', 51, NOW()),
( 'Chilcayoc', 51, NOW()),
( 'Huacaña', 51, NOW()),
( 'Morcolla', 51, NOW()),
( 'Paico', 51, NOW()),
( 'San Pedro de Larcay', 51, NOW()),
( 'San Salvador de Quije', 51, NOW()),
( 'Santiago de Paucaray', 51, NOW()),
( 'Soras', 51, NOW()),
( 'Huancapi', 52, NOW()),
( 'Alcamenca', 52, NOW()),
( 'Apongo', 52, NOW()),
( 'Asquipata', 52, NOW()),
( 'Canaria', 52, NOW()),
( 'Cayara', 52, NOW()),
( 'Colca', 52, NOW()),
( 'Huamanquiquia', 52, NOW()),
( 'Huancaraylla', 52, NOW()),
( 'Hualla', 52, NOW()),
( 'Sarhua', 52, NOW()),
( 'Vilcanchos', 52, NOW()),
( 'Vilcas Huaman', 53, NOW()),
( 'Accomarca', 53, NOW()),
( 'Carhuanca', 53, NOW()),
( 'Concepción', 53, NOW()),
( 'Huambalpa', 53, NOW()),
( 'Independencia', 53, NOW()),
( 'Saurama', 53, NOW()),
( 'Vischongo', 53, NOW()),
( 'Cajamarca', 54, NOW()),
( 'Asunción', 54, NOW()),
( 'Chetilla', 54, NOW()),
( 'Cospan', 54, NOW()),
( 'Encañada', 54, NOW()),
( 'Jesús', 54, NOW()),
( 'Llacanora', 54, NOW()),
( 'Los Baños del Inca', 54, NOW()),
( 'Magdalena', 54, NOW()),
( 'Matara', 54, NOW()),
( 'Namora', 54, NOW()),
( 'San Juan', 54, NOW()),
( 'Cajabamba', 55, NOW()),
( 'Cachachi', 55, NOW()),
( 'Condebamba', 55, NOW()),
( 'Sitacocha', 55, NOW()),
( 'Celendín', 56, NOW()),
( 'Chumuch', 56, NOW()),
( 'Cortegana', 56, NOW()),
( 'Huasmin', 56, NOW()),
( 'Jorge Chávez', 56, NOW()),
( 'José Gálvez', 56, NOW()),
( 'Miguel Iglesias', 56, NOW()),
( 'Oxamarca', 56, NOW()),
( 'Sorochuco', 56, NOW()),
( 'Sucre', 56, NOW()),
( 'Utco', 56, NOW()),
( 'La Libertad de Pallan', 56, NOW()),
( 'Chota', 57, NOW()),
( 'Anguia', 57, NOW()),
( 'Chadin', 57, NOW()),
( 'Chiguirip', 57, NOW()),
( 'Chimban', 57, NOW()),
( 'Choropampa', 57, NOW()),
( 'Cochabamba', 57, NOW()),
( 'Conchan', 57, NOW()),
( 'Huambos', 57, NOW()),
( 'Lajas', 57, NOW()),
( 'Llama', 57, NOW()),
( 'Miracosta', 57, NOW()),
( 'Paccha', 57, NOW()),
( 'Pion', 57, NOW()),
( 'Querocoto', 57, NOW()),
( 'San Juan de Licupis', 57, NOW()),
( 'Tacabamba', 57, NOW()),
( 'Tocmoche', 57, NOW()),
( 'Chalamarca', 57, NOW()),
( 'Contumaza', 58, NOW()),
( 'Chilete', 58, NOW()),
( 'Cupisnique', 58, NOW()),
( 'Guzmango', 58, NOW()),
( 'San Benito', 58, NOW()),
( 'Santa Cruz de Toledo', 58, NOW()),
( 'Tantarica', 58, NOW()),
( 'Yonan', 58, NOW()),
( 'Cutervo', 59, NOW()),
( 'Callayuc', 59, NOW()),
( 'Choros', 59, NOW()),
( 'Cujillo', 59, NOW()),
( 'La Ramada', 59, NOW()),
( 'Pimpingos', 59, NOW()),
( 'Querocotillo', 59, NOW()),
( 'San Andrés de Cutervo', 59, NOW()),
( 'San Juan de Cutervo', 59, NOW()),
( 'San Luis de Lucma', 59, NOW()),
( 'Santa Cruz', 59, NOW()),
( 'Santo Domingo de la Capilla', 59, NOW()),
( 'Santo Tomas', 59, NOW()),
( 'Socota', 59, NOW()),
( 'Toribio Casanova', 59, NOW()),
( 'Bambamarca', 60, NOW()),
( 'Chugur', 60, NOW()),
( 'Hualgayoc', 60, NOW()),
( 'Jaén', 61, NOW()),
( 'Bellavista', 61, NOW()),
( 'Chontali', 61, NOW()),
( 'Colasay', 61, NOW()),
( 'Huabal', 61, NOW()),
( 'Las Pirias', 61, NOW()),
( 'Pomahuaca', 61, NOW()),
( 'Pucara', 61, NOW()),
( 'Sallique', 61, NOW()),
( 'San Felipe', 61, NOW()),
( 'San José del Alto', 61, NOW()),
( 'Santa Rosa', 61, NOW()),
( 'San Ignacio', 62, NOW()),
( 'Chirinos', 62, NOW()),
( 'Huarango', 62, NOW()),
( 'La Coipa', 62, NOW()),
( 'Namballe', 62, NOW()),
( 'San José de Lourdes', 62, NOW()),
( 'Tabaconas', 62, NOW()),
( 'Pedro Gálvez', 63, NOW()),
( 'Chancay', 63, NOW()),
( 'Eduardo Villanueva', 63, NOW()),
( 'Gregorio Pita', 63, NOW()),
( 'Ichocan', 63, NOW()),
( 'José Manuel Quiroz', 63, NOW()),
( 'José Sabogal', 63, NOW()),
( 'San Miguel', 64, NOW()),
( 'Bolívar', 64, NOW()),
( 'Calquis', 64, NOW()),
( 'Catilluc', 64, NOW()),
( 'El Prado', 64, NOW()),
( 'La Florida', 64, NOW()),
( 'Llapa', 64, NOW()),
( 'Nanchoc', 64, NOW()),
( 'Niepos', 64, NOW()),
( 'San Gregorio', 64, NOW()),
( 'San Silvestre de Cochan', 64, NOW()),
( 'Tongod', 64, NOW()),
( 'Unión Agua Blanca', 64, NOW()),
( 'San Pablo', 65, NOW()),
( 'San Bernardino', 65, NOW()),
( 'San Luis', 65, NOW()),
( 'Tumbaden', 65, NOW()),
( 'Santa Cruz', 66, NOW()),
( 'Andabamba', 66, NOW()),
( 'Catache', 66, NOW()),
( 'Chancaybaños', 66, NOW()),
( 'La Esperanza', 66, NOW()),
( 'Ninabamba', 66, NOW()),
( 'Pulan', 66, NOW()),
( 'Saucepampa', 66, NOW()),
( 'Sexi', 66, NOW()),
( 'Uticyacu', 66, NOW()),
( 'Yauyucan', 66, NOW()),
( 'Callao', 67, NOW()),
( 'Bellavista', 67, NOW()),
( 'Carmen de la Legua Reynoso', 67, NOW()),
( 'La Perla', 67, NOW()),
( 'La Punta', 67, NOW()),
( 'Ventanilla', 67, NOW()),
( 'Mi Perú', 67, NOW()),
( 'Cusco', 68, NOW()),
( 'Ccorca', 68, NOW()),
( 'Poroy', 68, NOW()),
( 'San Jerónimo', 68, NOW()),
( 'San Sebastian', 68, NOW()),
( 'Santiago', 68, NOW()),
( 'Saylla', 68, NOW()),
( 'Wanchaq', 68, NOW()),
( 'Acomayo', 69, NOW()),
( 'Acopia', 69, NOW()),
( 'Acos', 69, NOW()),
( 'Mosoc Llacta', 69, NOW()),
( 'Pomacanchi', 69, NOW()),
( 'Rondocan', 69, NOW()),
( 'Sangarara', 69, NOW()),
( 'Anta', 70, NOW()),
( 'Ancahuasi', 70, NOW()),
( 'Cachimayo', 70, NOW()),
( 'Chinchaypujio', 70, NOW()),
( 'Huarocondo', 70, NOW()),
( 'Limatambo', 70, NOW()),
( 'Mollepata', 70, NOW()),
( 'Pucyura', 70, NOW()),
( 'Zurite', 70, NOW()),
( 'Calca', 71, NOW()),
( 'Coya', 71, NOW()),
( 'Lamay', 71, NOW()),
( 'Lares', 71, NOW()),
( 'Pisac', 71, NOW()),
( 'San Salvador', 71, NOW()),
( 'Taray', 71, NOW()),
( 'Yanatile', 71, NOW()),
( 'Yanaoca', 72, NOW()),
( 'Checca', 72, NOW()),
( 'Kunturkanki', 72, NOW()),
( 'Langui', 72, NOW()),
( 'Layo', 72, NOW()),
( 'Pampamarca', 72, NOW()),
( 'Quehue', 72, NOW()),
( 'Tupac Amaru', 72, NOW()),
( 'Sicuani', 73, NOW()),
( 'Checacupe', 73, NOW()),
( 'Combapata', 73, NOW()),
( 'Marangani', 73, NOW()),
( 'Pitumarca', 73, NOW()),
( 'San Pablo', 73, NOW()),
( 'San Pedro', 73, NOW()),
( 'Tinta', 73, NOW()),
( 'Santo Tomas', 74, NOW()),
( 'Capacmarca', 74, NOW()),
( 'Chamaca', 74, NOW()),
( 'Colquemarca', 74, NOW()),
( 'Livitaca', 74, NOW()),
( 'Llusco', 74, NOW()),
( 'Quiñota', 74, NOW()),
( 'Velille', 74, NOW()),
( 'Espinar', 75, NOW()),
( 'Condoroma', 75, NOW()),
( 'Coporaque', 75, NOW()),
( 'Ocoruro', 75, NOW()),
( 'Pallpata', 75, NOW()),
( 'Pichigua', 75, NOW()),
( 'Suyckutambo', 75, NOW()),
( 'Alto Pichigua', 75, NOW()),
( 'Santa Ana', 76, NOW()),
( 'Echarate', 76, NOW()),
( 'Huayopata', 76, NOW()),
( 'Maranura', 76, NOW()),
( 'Ocobamba', 76, NOW()),
( 'Quellouno', 76, NOW()),
( 'Kimbiri', 76, NOW()),
( 'Santa Teresa', 76, NOW()),
( 'Vilcabamba', 76, NOW()),
( 'Pichari', 76, NOW()),
( 'Inkawasi', 76, NOW()),
( 'Villa Virgen', 76, NOW()),
( 'Villa Kintiarina', 76, NOW()),
( 'Megantoni', 76, NOW()),
( 'Paruro', 77, NOW()),
( 'Accha', 77, NOW()),
( 'Ccapi', 77, NOW()),
( 'Colcha', 77, NOW()),
( 'Huanoquite', 77, NOW()),
( 'Omachaç', 77, NOW()),
( 'Paccaritambo', 77, NOW()),
( 'Pillpinto', 77, NOW()),
( 'Yaurisque', 77, NOW()),
( 'Paucartambo', 78, NOW()),
( 'Caicay', 78, NOW()),
( 'Challabamba', 78, NOW()),
( 'Colquepata', 78, NOW()),
( 'Huancarani', 78, NOW()),
( 'Kosñipata', 78, NOW()),
( 'Urcos', 79, NOW()),
( 'Andahuaylillas', 79, NOW()),
( 'Camanti', 79, NOW()),
( 'Ccarhuayo', 79, NOW()),
( 'Ccatca', 79, NOW()),
( 'Cusipata', 79, NOW()),
( 'Huaro', 79, NOW()),
( 'Lucre', 79, NOW()),
( 'Marcapata', 79, NOW()),
( 'Ocongate', 79, NOW()),
( 'Oropesa', 79, NOW()),
( 'Quiquijana', 79, NOW()),
( 'Urubamba', 80, NOW()),
( 'Chinchero', 80, NOW()),
( 'Huayllabamba', 80, NOW()),
( 'Machupicchu', 80, NOW()),
( 'Maras', 80, NOW()),
( 'Ollantaytambo', 80, NOW()),
( 'Yucay', 80, NOW()),
( 'Huancavelica', 81, NOW()),
( 'Acobambilla', 81, NOW()),
( 'Acoria', 81, NOW()),
( 'Conayca', 81, NOW()),
( 'Cuenca', 81, NOW()),
( 'Huachocolpa', 81, NOW()),
( 'Huayllahuara', 81, NOW()),
( 'Izcuchaca', 81, NOW()),
( 'Laria', 81, NOW()),
( 'Manta', 81, NOW()),
( 'Mariscal Cáceres', 81, NOW()),
( 'Moya', 81, NOW()),
( 'Nuevo Occoro', 81, NOW()),
( 'Palca', 81, NOW()),
( 'Pilchaca', 81, NOW()),
( 'Vilca', 81, NOW()),
( 'Yauli', 81, NOW()),
( 'Ascensión', 81, NOW()),
( 'Huando', 81, NOW()),
( 'Acobamba', 82, NOW()),
( 'Andabamba', 82, NOW()),
( 'Anta', 82, NOW()),
( 'Caja', 82, NOW()),
( 'Marcas', 82, NOW()),
( 'Paucara', 82, NOW()),
( 'Pomacocha', 82, NOW()),
( 'Rosario', 82, NOW()),
( 'Lircay', 83, NOW()),
( 'Anchonga', 83, NOW()),
( 'Callanmarca', 83, NOW()),
( 'Ccochaccasa', 83, NOW()),
( 'Chincho', 83, NOW()),
( 'Congalla', 83, NOW()),
( 'Huanca-Huanca', 83, NOW()),
( 'Huayllay Grande', 83, NOW()),
( 'Julcamarca', 83, NOW()),
( 'San Antonio de Antaparco', 83, NOW()),
( 'Santo Tomas de Pata', 83, NOW()),
( 'Secclla', 83, NOW()),
( 'Castrovirreyna', 84, NOW()),
( 'Arma', 84, NOW()),
( 'Aurahua', 84, NOW()),
( 'Capillas', 84, NOW()),
( 'Chupamarca', 84, NOW()),
( 'Cocas', 84, NOW()),
( 'Huachos', 84, NOW()),
( 'Huamatambo', 84, NOW()),
( 'Mollepampa', 84, NOW()),
( 'San Juan', 84, NOW()),
( 'Santa Ana', 84, NOW()),
( 'Tantara', 84, NOW()),
( 'Ticrapo', 84, NOW()),
( 'Churcampa', 85, NOW()),
( 'Anco', 85, NOW()),
( 'Chinchihuasi', 85, NOW()),
( 'El Carmen', 85, NOW()),
( 'La Merced', 85, NOW()),
( 'Locroja', 85, NOW()),
( 'Paucarbamba', 85, NOW()),
( 'San Miguel de Mayocc', 85, NOW()),
( 'San Pedro de Coris', 85, NOW()),
( 'Pachamarca', 85, NOW()),
( 'Cosme', 85, NOW()),
( 'Huaytara', 86, NOW()),
( 'Ayavi', 86, NOW()),
( 'Córdova', 86, NOW()),
( 'Huayacundo Arma', 86, NOW()),
( 'Laramarca', 86, NOW()),
( 'Ocoyo', 86, NOW()),
( 'Pilpichaca', 86, NOW()),
( 'Querco', 86, NOW()),
( 'Quito-Arma', 86, NOW()),
( 'San Antonio de Cusicancha', 86, NOW()),
( 'San Francisco de Sangayaico', 86, NOW()),
( 'San Isidro', 86, NOW()),
( 'Santiago de Chocorvos', 86, NOW()),
( 'Santiago de Quirahuara', 86, NOW()),
( 'Santo Domingo de Capillas', 86, NOW()),
( 'Tambo', 86, NOW()),
( 'Pampas', 87, NOW()),
( 'Acostambo', 87, NOW()),
( 'Acraquia', 87, NOW()),
( 'Ahuaycha', 87, NOW()),
( 'Colcabamba', 87, NOW()),
( 'Daniel Hernández', 87, NOW()),
( 'Huachocolpa', 87, NOW()),
( 'Huaribamba', 87, NOW()),
( 'Ñahuimpuquio', 87, NOW()),
( 'Pazos', 87, NOW()),
( 'Quishuar', 87, NOW()),
( 'Salcabamba', 87, NOW()),
( 'Salcahuasi', 87, NOW()),
( 'San Marcos de Rocchac', 87, NOW()),
( 'Surcubamba', 87, NOW()),
( 'Tintay Puncu', 87, NOW()),
( 'Quichuas', 87, NOW()),
( 'Andaymarca', 87, NOW()),
( 'Roble', 87, NOW()),
( 'Pichos', 87, NOW()),
( 'Santiago de Tucuma', 87, NOW()),
( 'Huanuco', 88, NOW()),
( 'Amarilis', 88, NOW()),
( 'Chinchao', 88, NOW()),
( 'Churubamba', 88, NOW()),
( 'Margos', 88, NOW()),
( 'Quisqui (Kichki)', 88, NOW()),
( 'San Francisco de Cayran', 88, NOW()),
( 'San Pedro de Chaulan', 88, NOW()),
( 'Santa María del Valle', 88, NOW()),
( 'Yarumayo', 88, NOW()),
( 'Pillco Marca', 88, NOW()),
( 'Yacus', 88, NOW()),
( 'San Pablo de Pillao', 88, NOW()),
( 'Ambo', 89, NOW()),
( 'Cayna', 89, NOW()),
( 'Colpas', 89, NOW()),
( 'Conchamarca', 89, NOW()),
( 'Huacar', 89, NOW()),
( 'San Francisco', 89, NOW()),
( 'San Rafael', 89, NOW()),
( 'Tomay Kichwa', 89, NOW()),
( 'La Unión', 90, NOW()),
( 'Chuquis', 90, NOW()),
( 'Marías', 90, NOW()),
( 'Pachas', 90, NOW()),
( 'Quivilla', 90, NOW()),
( 'Ripan', 90, NOW()),
( 'Shunqui', 90, NOW()),
( 'Sillapata', 90, NOW()),
( 'Yanas', 90, NOW()),
( 'Huacaybamba', 91, NOW()),
( 'Canchabamba', 91, NOW()),
( 'Cochabamba', 91, NOW()),
( 'Pinra', 91, NOW()),
( 'Llata', 92, NOW()),
( 'Arancay', 92, NOW()),
( 'Chavín de Pariarca', 92, NOW()),
( 'Jacas Grande', 92, NOW()),
( 'Jircan', 92, NOW()),
( 'Miraflores', 92, NOW()),
( 'Monzón', 92, NOW()),
( 'Punchao', 92, NOW()),
( 'Puños', 92, NOW()),
( 'Singa', 92, NOW()),
( 'Tantamayo', 92, NOW()),
( 'Rupa-Rupa', 93, NOW()),
( 'Daniel Alomía Robles', 93, NOW()),
( 'Hermílio Valdizan', 93, NOW()),
( 'José Crespo y Castillo', 93, NOW()),
( 'Luyando', 93, NOW()),
( 'Mariano Damaso Beraun', 93, NOW()),
( 'Pucayacu', 93, NOW()),
( 'Castillo Grande', 93, NOW()),
( 'Pueblo Nuevo', 93, NOW()),
( 'Santo Domingo de Anda', 93, NOW()),
( 'Huacrachuco', 94, NOW()),
( 'Cholon', 94, NOW()),
( 'San Buenaventura', 94, NOW()),
( 'La Morada', 94, NOW()),
( 'Santa Rosa de Alto Yanajanca', 94, NOW()),
( 'Panao', 95, NOW()),
( 'Chaglla', 95, NOW()),
( 'Molino', 95, NOW()),
( 'Umari', 95, NOW()),
( 'Puerto Inca', 96, NOW()),
( 'Codo del Pozuzo', 96, NOW()),
( 'Honoria', 96, NOW()),
( 'Tournavista', 96, NOW()),
( 'Yuyapichis', 96, NOW()),
( 'Jesús', 97, NOW()),
( 'Baños', 97, NOW()),
( 'Jivia', 97, NOW()),
( 'Queropalca', 97, NOW()),
( 'Rondos', 97, NOW()),
( 'San Francisco de Asís', 97, NOW()),
( 'San Miguel de Cauri', 97, NOW()),
( 'Chavinillo', 98, NOW()),
( 'Cahuac', 98, NOW()),
( 'Chacabamba', 98, NOW()),
( 'Aparicio Pomares', 98, NOW()),
( 'Jacas Chico', 98, NOW()),
( 'Obas', 98, NOW()),
( 'Pampamarca', 98, NOW()),
( 'Choras', 98, NOW()),
( 'Ica', 99, NOW()),
( 'La Tinguiña', 99, NOW()),
( 'Los Aquijes', 99, NOW()),
( 'Ocucaje', 99, NOW()),
( 'Pachacutec', 99, NOW()),
( 'Parcona', 99, NOW()),
( 'Pueblo Nuevo', 99, NOW()),
( 'Salas', 99, NOW()),
( 'San José de Los Molinos', 99, NOW()),
( 'San Juan Bautista', 99, NOW()),
( 'Santiago', 99, NOW()),
( 'Subtanjalla', 99, NOW()),
( 'Tate', 99, NOW()),
( 'Yauca del Rosario', 99, NOW()),
( 'Chincha Alta', 100, NOW()),
( 'Alto Laran', 100, NOW()),
( 'Chavin', 100, NOW()),
( 'Chincha Baja', 100, NOW()),
( 'El Carmen', 100, NOW()),
( 'Grocio Prado', 100, NOW()),
( 'Pueblo Nuevo', 100, NOW()),
( 'San Juan de Yanac', 100, NOW()),
( 'San Pedro de Huacarpana', 100, NOW()),
( 'Sunampe', 100, NOW()),
( 'Tambo de Mora', 100, NOW()),
( 'Nasca', 101, NOW()),
( 'Changuillo', 101, NOW()),
( 'El Ingenio', 101, NOW()),
( 'Marcona', 101, NOW()),
( 'Vista Alegre', 101, NOW()),
( 'Palpa', 102, NOW()),
( 'Llipata', 102, NOW()),
( 'Río Grande', 102, NOW()),
( 'Santa Cruz', 102, NOW()),
( 'Tibillo', 102, NOW()),
( 'Pisco', 103, NOW()),
( 'Huancano', 103, NOW()),
( 'Humay', 103, NOW()),
( 'Independencia', 103, NOW()),
( 'Paracas', 103, NOW()),
( 'San Andrés', 103, NOW()),
( 'San Clemente', 103, NOW()),
( 'Tupac Amaru Inca', 103, NOW()),
( 'Huancayo', 104, NOW()),
( 'Carhuacallanga', 104, NOW()),
( 'Chacapampa', 104, NOW()),
( 'Chicche', 104, NOW()),
( 'Chilca', 104, NOW()),
( 'Chongos Alto', 104, NOW()),
( 'Chupuro', 104, NOW()),
( 'Colca', 104, NOW()),
( 'Cullhuas', 104, NOW()),
( 'El Tambo', 104, NOW()),
( 'Huacrapuquio', 104, NOW()),
( 'Hualhuas', 104, NOW()),
( 'Huancan', 104, NOW()),
( 'Huasicancha', 104, NOW()),
( 'Huayucachi', 104, NOW()),
( 'Ingenio', 104, NOW()),
( 'Pariahuanca', 104, NOW()),
( 'Pilcomayo', 104, NOW()),
( 'Pucara', 104, NOW()),
( 'Quichuay', 104, NOW()),
( 'Quilcas', 104, NOW()),
( 'San Agustín', 104, NOW()),
( 'San Jerónimo de Tunan', 104, NOW()),
( 'Saño', 104, NOW()),
( 'Sapallanga', 104, NOW()),
( 'Sicaya', 104, NOW()),
( 'Santo Domingo de Acobamba', 104, NOW()),
( 'Viques', 104, NOW()),
( 'Concepción', 105, NOW()),
( 'Aco', 105, NOW()),
( 'Andamarca', 105, NOW()),
( 'Chambara', 105, NOW()),
( 'Cochas', 105, NOW()),
( 'Comas', 105, NOW()),
( 'Heroínas Toledo', 105, NOW()),
( 'Manzanares', 105, NOW()),
( 'Mariscal Castilla', 105, NOW()),
( 'Matahuasi', 105, NOW()),
( 'Mito', 105, NOW()),
( 'Nueve de Julio', 105, NOW()),
( 'Orcotuna', 105, NOW()),
( 'San José de Quero', 105, NOW()),
( 'Santa Rosa de Ocopa', 105, NOW()),
( 'Chanchamayo', 106, NOW()),
( 'Perene', 106, NOW()),
( 'Pichanaqui', 106, NOW()),
( 'San Luis de Shuaro', 106, NOW()),
( 'San Ramón', 106, NOW()),
( 'Vitoc', 106, NOW()),
( 'Jauja', 107, NOW()),
( 'Acolla', 107, NOW()),
( 'Apata', 107, NOW()),
( 'Ataura', 107, NOW()),
( 'Canchayllo', 107, NOW()),
( 'Curicaca', 107, NOW()),
( 'El Mantaro', 107, NOW()),
( 'Huamali', 107, NOW()),
( 'Huaripampa', 107, NOW()),
( 'Huertas', 107, NOW()),
( 'Janjaillo', 107, NOW()),
( 'Julcán', 107, NOW()),
( 'Leonor Ordóñez', 107, NOW()),
( 'Llocllapampa', 107, NOW()),
( 'Marco', 107, NOW()),
( 'Masma', 107, NOW()),
( 'Masma Chicche', 107, NOW()),
( 'Molinos', 107, NOW()),
( 'Monobamba', 107, NOW()),
( 'Muqui', 107, NOW()),
( 'Muquiyauyo', 107, NOW()),
( 'Paca', 107, NOW()),
( 'Paccha', 107, NOW()),
( 'Pancan', 107, NOW()),
( 'Parco', 107, NOW()),
( 'Pomacancha', 107, NOW()),
( 'Ricran', 107, NOW()),
( 'San Lorenzo', 107, NOW()),
( 'San Pedro de Chunan', 107, NOW()),
( 'Sausa', 107, NOW()),
( 'Sincos', 107, NOW()),
( 'Tunan Marca', 107, NOW()),
( 'Yauli', 107, NOW()),
( 'Yauyos', 107, NOW()),
( 'Junin', 108, NOW()),
( 'Carhuamayo', 108, NOW()),
( 'Ondores', 108, NOW()),
( 'Ulcumayo', 108, NOW()),
( 'Satipo', 109, NOW()),
( 'Coviriali', 109, NOW()),
( 'Llaylla', 109, NOW()),
( 'Mazamari', 109, NOW()),
( 'Pampa Hermosa', 109, NOW()),
( 'Pangoa', 109, NOW()),
( 'Río Negro', 109, NOW()),
( 'Río Tambo', 109, NOW()),
( 'Vizcatan del Ene', 109, NOW()),
( 'Tarma', 110, NOW()),
( 'Acobamba', 110, NOW()),
( 'Huaricolca', 110, NOW()),
( 'Huasahuasi', 110, NOW()),
( 'La Unión', 110, NOW()),
( 'Palca', 110, NOW()),
( 'Palcamayo', 110, NOW()),
( 'San Pedro de Cajas', 110, NOW()),
( 'Tapo', 110, NOW()),
( 'La Oroya', 111, NOW()),
( 'Chacapalpa', 111, NOW()),
( 'Huay-Huay', 111, NOW()),
( 'Marcapomacocha', 111, NOW()),
( 'Morococha', 111, NOW()),
( 'Paccha', 111, NOW()),
( 'Santa Bárbara de Carhuacayan', 111, NOW()),
( 'Santa Rosa de Sacco', 111, NOW()),
( 'Suitucancha', 111, NOW()),
( 'Yauli', 111, NOW()),
( 'Chupaca', 112, NOW()),
( 'Ahuac', 112, NOW()),
( 'Chongos Bajo', 112, NOW()),
( 'Huachac', 112, NOW()),
( 'Huamancaca Chico', 112, NOW()),
( 'San Juan de Iscos', 112, NOW()),
( 'San Juan de Jarpa', 112, NOW()),
( 'Tres de Diciembre', 112, NOW()),
( 'Yanacancha', 112, NOW()),
( 'Trujillo', 113, NOW()),
( 'El Porvenir', 113, NOW()),
( 'Florencia de Mora', 113, NOW()),
( 'Huanchaco', 113, NOW()),
( 'La Esperanza', 113, NOW()),
( 'Laredo', 113, NOW()),
( 'Moche', 113, NOW()),
( 'Poroto', 113, NOW()),
( 'Salaverry', 113, NOW()),
( 'Simbal', 113, NOW()),
( 'Victor Larco Herrera', 113, NOW()),
( 'Ascope', 114, NOW()),
( 'Chicama', 114, NOW()),
( 'Chocope', 114, NOW()),
( 'Magdalena de Cao', 114, NOW()),
( 'Paijan', 114, NOW()),
( 'Rázuri', 114, NOW()),
( 'Santiago de Cao', 114, NOW()),
( 'Casa Grande', 114, NOW()),
( 'Bolívar', 115, NOW()),
( 'Bambamarca', 115, NOW()),
( 'Condormarca', 115, NOW()),
( 'Longotea', 115, NOW()),
( 'Uchumarca', 115, NOW()),
( 'Ucuncha', 115, NOW()),
( 'Chepen', 116, NOW()),
( 'Pacanga', 116, NOW()),
( 'Pueblo Nuevo', 116, NOW()),
( 'Julcan', 117, NOW()),
( 'Calamarca', 117, NOW()),
( 'Carabamba', 117, NOW()),
( 'Huaso', 117, NOW()),
( 'Otuzco', 118, NOW()),
( 'Agallpampa', 118, NOW()),
( 'Charat', 118, NOW()),
( 'Huaranchal', 118, NOW()),
( 'La Cuesta', 118, NOW()),
( 'Mache', 118, NOW()),
( 'Paranday', 118, NOW()),
( 'Salpo', 118, NOW()),
( 'Sinsicap', 118, NOW()),
( 'Usquil', 118, NOW()),
( 'San Pedro de Lloc', 119, NOW()),
( 'Guadalupe', 119, NOW()),
( 'Jequetepeque', 119, NOW()),
( 'Pacasmayo', 119, NOW()),
( 'San José', 119, NOW()),
( 'Tayabamba', 120, NOW()),
( 'Buldibuyo', 120, NOW()),
( 'Chillia', 120, NOW()),
( 'Huancaspata', 120, NOW()),
( 'Huaylillas', 120, NOW()),
( 'Huayo', 120, NOW()),
( 'Ongon', 120, NOW()),
( 'Parcoy', 120, NOW()),
( 'Pataz', 120, NOW()),
( 'Pias', 120, NOW()),
( 'Santiago de Challas', 120, NOW()),
( 'Taurija', 120, NOW()),
( 'Urpay', 120, NOW()),
( 'Huamachuco', 121, NOW()),
( 'Chugay', 121, NOW()),
( 'Cochorco', 121, NOW()),
( 'Curgos', 121, NOW()),
( 'Marcabal', 121, NOW()),
( 'Sanagoran', 121, NOW()),
( 'Sarin', 121, NOW()),
( 'Sartimbamba', 121, NOW()),
( 'Santiago de Chuco', 122, NOW()),
( 'Angasmarca', 122, NOW()),
( 'Cachicadan', 122, NOW()),
( 'Mollebamba', 122, NOW()),
( 'Mollepata', 122, NOW()),
( 'Quiruvilca', 122, NOW()),
( 'Santa Cruz de Chuca', 122, NOW()),
( 'Sitabamba', 122, NOW()),
( 'Cascas', 123, NOW()),
( 'Lucma', 123, NOW()),
( 'Marmot', 123, NOW()),
( 'Sayapullo', 123, NOW()),
( 'Viru', 124, NOW()),
( 'Chao', 124, NOW()),
( 'Guadalupito', 124, NOW()),
( 'Chiclayo', 125, NOW()),
( 'Chongoyape', 125, NOW()),
( 'Eten', 125, NOW()),
( 'Eten Puerto', 125, NOW()),
( 'José Leonardo Ortiz', 125, NOW()),
( 'La Victoria', 125, NOW()),
( 'Lagunas', 125, NOW()),
( 'Monsefu', 125, NOW()),
( 'Nueva Arica', 125, NOW()),
( 'Oyotun', 125, NOW()),
( 'Picsi', 125, NOW()),
( 'Pimentel', 125, NOW()),
( 'Reque', 125, NOW()),
( 'Santa Rosa', 125, NOW()),
( 'Saña', 125, NOW()),
( 'Cayalti', 125, NOW()),
( 'Patapo', 125, NOW()),
( 'Pomalca', 125, NOW()),
( 'Pucala', 125, NOW()),
( 'Tuman', 125, NOW()),
( 'Ferreñafe', 126, NOW()),
( 'Cañaris', 126, NOW()),
( 'Incahuasi', 126, NOW()),
( 'Manuel Antonio Mesones Muro', 126, NOW()),
( 'Pitipo', 126, NOW()),
( 'Pueblo Nuevo', 126, NOW()),
( 'Lambayeque', 127, NOW()),
( 'Chochope', 127, NOW()),
( 'Illimo', 127, NOW()),
( 'Jayanca', 127, NOW()),
( 'Mochumi', 127, NOW()),
( 'Morrope', 127, NOW()),
( 'Motupe', 127, NOW()),
( 'Olmos', 127, NOW()),
( 'Pacora', 127, NOW()),
( 'Salas', 127, NOW()),
( 'San José', 127, NOW()),
( 'Tucume', 127, NOW()),
( 'Lima', 128, NOW()),
( 'Ancón', 128, NOW()),
( 'Ate', 128, NOW()),
( 'Barranco', 128, NOW()),
( 'Breña', 128, NOW()),
( 'Carabayllo', 128, NOW()),
( 'Chaclacayo', 128, NOW()),
( 'Chorrillos', 128, NOW()),
( 'Cieneguilla', 128, NOW()),
( 'Comas', 128, NOW()),
( 'El Agustino', 128, NOW()),
( 'Independencia', 128, NOW()),
( 'Jesús María', 128, NOW()),
( 'La Molina', 128, NOW()),
( 'La Victoria', 128, NOW()),
( 'Lince', 128, NOW()),
( 'Los Olivos', 128, NOW()),
( 'Lurigancho', 128, NOW()),
( 'Lurin', 128, NOW()),
( 'Magdalena del Mar', 128, NOW()),
( 'Pueblo Libre', 128, NOW()),
( 'Miraflores', 128, NOW()),
( 'Pachacamac', 128, NOW()),
( 'Pucusana', 128, NOW()),
( 'Puente Piedra', 128, NOW()),
( 'Punta Hermosa', 128, NOW()),
( 'Punta Negra', 128, NOW()),
( 'Rímac', 128, NOW()),
( 'San Bartolo', 128, NOW()),
( 'San Borja', 128, NOW()),
( 'San Isidro', 128, NOW()),
( 'San Juan de Lurigancho', 128, NOW()),
( 'San Juan de Miraflores', 128, NOW()),
( 'San Luis', 128, NOW()),
( 'San Martín de Porres', 128, NOW()),
( 'San Miguel', 128, NOW()),
( 'Santa Anita', 128, NOW()),
( 'Santa María del Mar', 128, NOW()),
( 'Santa Rosa', 128, NOW()),
( 'Santiago de Surco', 128, NOW()),
( 'Surquillo', 128, NOW()),
( 'Villa El Salvador', 128, NOW()),
( 'Villa María del Triunfo', 128, NOW()),
( 'Barranca', 129, NOW()),
( 'Paramonga', 129, NOW()),
( 'Pativilca', 129, NOW()),
( 'Supe', 129, NOW()),
( 'Supe Puerto', 129, NOW()),
( 'Cajatambo', 130, NOW()),
( 'Copa', 130, NOW()),
( 'Gorgor', 130, NOW()),
( 'Huancapon', 130, NOW()),
( 'Manas', 130, NOW()),
( 'Canta', 131, NOW()),
( 'Arahuay', 131, NOW()),
( 'Huamantanga', 131, NOW()),
( 'Huaros', 131, NOW()),
( 'Lachaqui', 131, NOW()),
( 'San Buenaventura', 131, NOW()),
( 'San Vicente de Cañete', 132, NOW()),
( 'Asia', 132, NOW()),
( 'Calango', 132, NOW()),
( 'Cerro Azul', 132, NOW()),
( 'Chilca', 132, NOW()),
( 'Coayllo', 132, NOW()),
( 'Imperial', 132, NOW()),
( 'Lunahuana', 132, NOW()),
( 'Mala', 132, NOW()),
( 'Nuevo Imperial', 132, NOW()),
( 'Pacaran', 132, NOW()),
( 'Quilmana', 132, NOW()),
( 'San Antonio', 132, NOW()),
( 'San Luis', 132, NOW()),
( 'Santa Cruz de Flores', 132, NOW()),
( 'Zúñiga', 132, NOW()),
( 'Huaral', 133, NOW()),
( 'Atavillos Alto', 133, NOW()),
( 'Atavillos Bajo', 133, NOW()),
( 'Aucallama', 133, NOW()),
( 'Chancay', 133, NOW()),
( 'Ihuari', 133, NOW()),
( 'Lampian', 133, NOW()),
( 'Pacaraos', 133, NOW()),
( 'San Miguel de Acos', 133, NOW()),
( 'Santa Cruz de Andamarca', 133, NOW()),
( 'Sumbilca', 133, NOW()),
( 'Veintisiete de Noviembre', 133, NOW()),
( 'Matucana', 134, NOW()),
( 'Antioquia', 134, NOW()),
( 'Callahuanca', 134, NOW()),
( 'Carampoma', 134, NOW()),
( 'Chicla', 134, NOW()),
( 'Cuenca', 134, NOW()),
( 'Huachupampa', 134, NOW()),
( 'Huanza', 134, NOW()),
( 'Huarochiri', 134, NOW()),
( 'Lahuaytambo', 134, NOW()),
( 'Langa', 134, NOW()),
( 'Laraos', 134, NOW()),
( 'Mariatana', 134, NOW()),
( 'Ricardo Palma', 134, NOW()),
( 'San Andrés de Tupicocha', 134, NOW()),
( 'San Antonio', 134, NOW()),
( 'San Bartolomé', 134, NOW()),
( 'San Damian', 134, NOW()),
( 'San Juan de Iris', 134, NOW()),
( 'San Juan de Tantaranche', 134, NOW()),
( 'San Lorenzo de Quinti', 134, NOW()),
( 'San Mateo', 134, NOW()),
( 'San Mateo de Otao', 134, NOW()),
( 'San Pedro de Casta', 134, NOW()),
( 'San Pedro de Huancayre', 134, NOW()),
( 'Sangallaya', 134, NOW()),
( 'Santa Cruz de Cocachacra', 134, NOW()),
( 'Santa Eulalia', 134, NOW()),
( 'Santiago de Anchucaya', 134, NOW()),
( 'Santiago de Tuna', 134, NOW()),
( 'Santo Domingo de Los Olleros', 134, NOW()),
( 'Surco', 134, NOW()),
( 'Huacho', 135, NOW()),
( 'Ambar', 135, NOW()),
( 'Caleta de Carquin', 135, NOW()),
( 'Checras', 135, NOW()),
( 'Hualmay', 135, NOW()),
( 'Huaura', 135, NOW()),
( 'Leoncio Prado', 135, NOW()),
( 'Paccho', 135, NOW()),
( 'Santa Leonor', 135, NOW()),
( 'Santa María', 135, NOW()),
( 'Sayan', 135, NOW()),
( 'Vegueta', 135, NOW()),
( 'Oyon', 136, NOW()),
( 'Andajes', 136, NOW()),
( 'Caujul', 136, NOW()),
( 'Cochamarca', 136, NOW()),
( 'Navan', 136, NOW()),
( 'Pachangara', 136, NOW()),
( 'Yauyos', 137, NOW()),
( 'Alis', 137, NOW()),
( 'Allauca', 137, NOW()),
( 'Ayaviri', 137, NOW()),
( 'Azángaro', 137, NOW()),
( 'Cacra', 137, NOW()),
( 'Carania', 137, NOW()),
( 'Catahuasi', 137, NOW()),
( 'Chocos', 137, NOW()),
( 'Cochas', 137, NOW()),
( 'Colonia', 137, NOW()),
( 'Hongos', 137, NOW()),
( 'Huampara', 137, NOW()),
( 'Huancaya', 137, NOW()),
( 'Huangascar', 137, NOW()),
( 'Huantan', 137, NOW()),
( 'Huañec', 137, NOW()),
( 'Laraos', 137, NOW()),
( 'Lincha', 137, NOW()),
( 'Madean', 137, NOW()),
( 'Miraflores', 137, NOW()),
( 'Omas', 137, NOW()),
( 'Putinza', 137, NOW()),
( 'Quinches', 137, NOW()),
( 'Quinocay', 137, NOW()),
( 'San Joaquín', 137, NOW()),
( 'San Pedro de Pilas', 137, NOW()),
( 'Tanta', 137, NOW()),
( 'Tauripampa', 137, NOW()),
( 'Tomas', 137, NOW()),
( 'Tupe', 137, NOW()),
( 'Viñac', 137, NOW()),
( 'Vitis', 137, NOW()),
( 'Iquitos', 138, NOW()),
( 'Alto Nanay', 138, NOW()),
( 'Fernando Lores', 138, NOW()),
( 'Indiana', 138, NOW()),
( 'Las Amazonas', 138, NOW()),
( 'Mazan', 138, NOW()),
( 'Napo', 138, NOW()),
( 'Punchana', 138, NOW()),
( 'Torres Causana', 138, NOW()),
( 'Belén', 138, NOW()),
( 'San Juan Bautista', 138, NOW()),
( 'Yurimaguas', 139, NOW()),
( 'Balsapuerto', 139, NOW()),
( 'Jeberos', 139, NOW()),
( 'Lagunas', 139, NOW()),
( 'Santa Cruz', 139, NOW()),
( 'Teniente Cesar López Rojas', 139, NOW()),
( 'Nauta', 140, NOW()),
( 'Parinari', 140, NOW()),
( 'Tigre', 140, NOW()),
( 'Trompeteros', 140, NOW()),
( 'Urarinas', 140, NOW()),
( 'Ramón Castilla', 141, NOW()),
( 'Pebas', 141, NOW()),
( 'Yavari', 141, NOW()),
( 'San Pablo', 141, NOW()),
( 'Requena', 142, NOW()),
( 'Alto Tapiche', 142, NOW()),
( 'Capelo', 142, NOW()),
( 'Emilio San Martín', 142, NOW()),
( 'Maquia', 142, NOW()),
( 'Puinahua', 142, NOW()),
( 'Saquena', 142, NOW()),
( 'Soplin', 142, NOW()),
( 'Tapiche', 142, NOW()),
( 'Jenaro Herrera', 142, NOW()),
( 'Yaquerana', 142, NOW()),
( 'Contamana', 143, NOW()),
( 'Inahuaya', 143, NOW()),
( 'Padre Márquez', 143, NOW()),
( 'Pampa Hermosa', 143, NOW()),
( 'Sarayacu', 143, NOW()),
( 'Vargas Guerra', 143, NOW()),
( 'Barranca', 144, NOW()),
( 'Cahuapanas', 144, NOW()),
( 'Manseriche', 144, NOW()),
( 'Morona', 144, NOW()),
( 'Pastaza', 144, NOW()),
( 'Andoas', 144, NOW()),
( 'Putumayo', 145, NOW()),
( 'Rosa Panduro', 145, NOW()),
( 'Teniente Manuel Clavero', 145, NOW()),
( 'Yaguas', 145, NOW()),
( 'Tambopata', 146, NOW()),
( 'Inambari', 146, NOW()),
( 'Las Piedras', 146, NOW()),
( 'Laberinto', 146, NOW()),
( 'Manu', 147, NOW()),
( 'Fitzcarrald', 147, NOW()),
( 'Madre de Dios', 147, NOW()),
( 'Huepetuhe', 147, NOW()),
( 'Iñapari', 148, NOW()),
( 'Iberia', 148, NOW()),
( 'Tahuamanu', 148, NOW()),
( 'Moquegua', 149, NOW()),
( 'Carumas', 149, NOW()),
( 'Cuchumbaya', 149, NOW()),
( 'Samegua', 149, NOW()),
( 'San Cristóbal', 149, NOW()),
( 'Torata', 149, NOW()),
( 'Omate', 150, NOW()),
( 'Chojata', 150, NOW()),
( 'Coalaque', 150, NOW()),
( 'Ichuña', 150, NOW()),
( 'La Capilla', 150, NOW()),
( 'Lloque', 150, NOW()),
( 'Matalaque', 150, NOW()),
( 'Puquina', 150, NOW()),
( 'Quinistaquillas', 150, NOW()),
( 'Ubinas', 150, NOW()),
( 'Yunga', 150, NOW()),
( 'Ilo', 151, NOW()),
( 'El Algarrobal', 151, NOW()),
( 'Pacocha', 151, NOW()),
( 'Chaupimarca', 152, NOW()),
( 'Huachon', 152, NOW()),
( 'Huariaca', 152, NOW()),
( 'Huayllay', 152, NOW()),
( 'Ninacaca', 152, NOW()),
( 'Pallanchacra', 152, NOW()),
( 'Paucartambo', 152, NOW()),
( 'San Francisco de Asís de Yarusyacan', 152, NOW()),
( 'Simon Bolívar', 152, NOW()),
( 'Ticlacayan', 152, NOW()),
( 'Tinyahuarco', 152, NOW()),
( 'Vicco', 152, NOW()),
( 'Yanacancha', 152, NOW()),
( 'Yanahuanca', 153, NOW()),
( 'Chacayan', 153, NOW()),
( 'Goyllarisquizga', 153, NOW()),
( 'Paucar', 153, NOW()),
( 'San Pedro de Pillao', 153, NOW()),
( 'Santa Ana de Tusi', 153, NOW()),
( 'Tapuc', 153, NOW()),
( 'Vilcabamba', 153, NOW()),
( 'Oxapampa', 154, NOW()),
( 'Chontabamba', 154, NOW()),
( 'Huancabamba', 154, NOW()),
( 'Palcazu', 154, NOW()),
( 'Pozuzo', 154, NOW()),
( 'Puerto Bermúdez', 154, NOW()),
( 'Villa Rica', 154, NOW()),
( 'Constitución', 154, NOW()),
( 'Piura', 155, NOW()),
( 'Castilla', 155, NOW()),
( 'Catacaos', 155, NOW()),
( 'Cura Mori', 155, NOW()),
( 'El Tallan', 155, NOW()),
( 'La Arena', 155, NOW()),
( 'La Unión', 155, NOW()),
( 'Las Lomas', 155, NOW()),
( 'Tambo Grande', 155, NOW()),
( 'Veintiseis de Octubre', 155, NOW()),
( 'Ayabaca', 156, NOW()),
( 'Frias', 156, NOW()),
( 'Jilili', 156, NOW()),
( 'Lagunas', 156, NOW()),
( 'Montero', 156, NOW()),
( 'Pacaipampa', 156, NOW()),
( 'Paimas', 156, NOW()),
( 'Sapillica', 156, NOW()),
( 'Sicchez', 156, NOW()),
( 'Suyo', 156, NOW()),
( 'Huancabamba', 157, NOW()),
( 'Canchaque', 157, NOW()),
( 'El Carmen de la Frontera', 157, NOW()),
( 'Huarmaca', 157, NOW()),
( 'Lalaquiz', 157, NOW()),
( 'San Miguel de El Faique', 157, NOW()),
( 'Sondor', 157, NOW()),
( 'Sondorillo', 157, NOW()),
( 'Chulucanas', 158, NOW()),
( 'Buenos Aires', 158, NOW()),
( 'Chalaco', 158, NOW()),
( 'La Matanza', 158, NOW()),
( 'Morropon', 158, NOW()),
( 'Salitral', 158, NOW()),
( 'San Juan de Bigote', 158, NOW()),
( 'Santa Catalina de Mossa', 158, NOW()),
( 'Santo Domingo', 158, NOW()),
( 'Yamango', 158, NOW()),
( 'Paita', 159, NOW()),
( 'Amotape', 159, NOW()),
( 'Arenal', 159, NOW()),
( 'Colan', 159, NOW()),
( 'La Huaca', 159, NOW()),
( 'Tamarindo', 159, NOW()),
( 'Vichayal', 159, NOW()),
( 'Sullana', 160, NOW()),
( 'Bellavista', 160, NOW()),
( 'Ignacio Escudero', 160, NOW()),
( 'Lancones', 160, NOW()),
( 'Marcavelica', 160, NOW()),
( 'Miguel Checa', 160, NOW()),
( 'Querecotillo', 160, NOW()),
( 'Salitral', 160, NOW()),
( 'Pariñas', 161, NOW()),
( 'El Alto', 161, NOW()),
( 'La Brea', 161, NOW()),
( 'Lobitos', 161, NOW()),
( 'Los Organos', 161, NOW()),
( 'Mancora', 161, NOW()),
( 'Sechura', 162, NOW()),
( 'Bellavista de la Unión', 162, NOW()),
( 'Bernal', 162, NOW()),
( 'Cristo Nos Valga', 162, NOW()),
( 'Vice', 162, NOW()),
( 'Rinconada Llicuar', 162, NOW()),
( 'Puno', 163, NOW()),
( 'Acora', 163, NOW()),
( 'Amantani', 163, NOW()),
( 'Atuncolla', 163, NOW()),
( 'Capachica', 163, NOW()),
( 'Chucuito', 163, NOW()),
( 'Coata', 163, NOW()),
( 'Huata', 163, NOW()),
( 'Mañazo', 163, NOW()),
( 'Paucarcolla', 163, NOW()),
( 'Pichacani', 163, NOW()),
( 'Plateria', 163, NOW()),
( 'San Antonio', 163, NOW()),
( 'Tiquillaca', 163, NOW()),
( 'Vilque', 163, NOW()),
( 'Azángaro', 164, NOW()),
( 'Achaya', 164, NOW()),
( 'Arapa', 164, NOW()),
( 'Asillo', 164, NOW()),
( 'Caminaca', 164, NOW()),
( 'Chupa', 164, NOW()),
( 'José Domingo Choquehuanca', 164, NOW()),
( 'Muñani', 164, NOW()),
( 'Potoni', 164, NOW()),
( 'Saman', 164, NOW()),
( 'San Anton', 164, NOW()),
( 'San José', 164, NOW()),
( 'San Juan de Salinas', 164, NOW()),
( 'Santiago de Pupuja', 164, NOW()),
( 'Tirapata', 164, NOW()),
( 'Macusani', 165, NOW()),
( 'Ajoyani', 165, NOW()),
( 'Ayapata', 165, NOW()),
( 'Coasa', 165, NOW()),
( 'Corani', 165, NOW()),
( 'Crucero', 165, NOW()),
( 'Ituata', 165, NOW()),
( 'Ollachea', 165, NOW()),
( 'San Gaban', 165, NOW()),
( 'Usicayos', 165, NOW()),
( 'Juli', 166, NOW()),
( 'Desaguadero', 166, NOW()),
( 'Huacullani', 166, NOW()),
( 'Kelluyo', 166, NOW()),
( 'Pisacoma', 166, NOW()),
( 'Pomata', 166, NOW()),
( 'Zepita', 166, NOW()),
( 'Ilave', 167, NOW()),
( 'Capazo', 167, NOW()),
( 'Pilcuyo', 167, NOW()),
( 'Santa Rosa', 167, NOW()),
( 'Conduriri', 167, NOW()),
( 'Huancane', 168, NOW()),
( 'Cojata', 168, NOW()),
( 'Huatasani', 168, NOW()),
( 'Inchupalla', 168, NOW()),
( 'Pusi', 168, NOW()),
( 'Rosaspata', 168, NOW()),
( 'Taraco', 168, NOW()),
( 'Vilque Chico', 168, NOW()),
( 'Lampa', 169, NOW()),
( 'Cabanilla', 169, NOW()),
( 'Calapuja', 169, NOW()),
( 'Nicasio', 169, NOW()),
( 'Ocuviri', 169, NOW()),
( 'Palca', 169, NOW()),
( 'Paratia', 169, NOW()),
( 'Pucara', 169, NOW()),
( 'Santa Lucia', 169, NOW()),
( 'Vilavila', 169, NOW()),
( 'Ayaviri', 170, NOW()),
( 'Antauta', 170, NOW()),
( 'Cupi', 170, NOW()),
( 'Llalli', 170, NOW()),
( 'Macari', 170, NOW()),
( 'Nuñoa', 170, NOW()),
( 'Orurillo', 170, NOW()),
( 'Santa Rosa', 170, NOW()),
( 'Umachiri', 170, NOW()),
( 'Moho', 171, NOW()),
( 'Conima', 171, NOW()),
( 'Huayrapata', 171, NOW()),
( 'Tilali', 171, NOW()),
( 'Putina', 172, NOW()),
( 'Ananea', 172, NOW()),
( 'Pedro Vilca Apaza', 172, NOW()),
( 'Quilcapuncu', 172, NOW()),
( 'Sina', 172, NOW()),
( 'Juliaca', 173, NOW()),
( 'Cabana', 173, NOW()),
( 'Cabanillas', 173, NOW()),
( 'Caracoto', 173, NOW()),
( 'San Miguel', 173, NOW()),
( 'Sandia', 174, NOW()),
( 'Cuyocuyo', 174, NOW()),
( 'Limbani', 174, NOW()),
( 'Patambuco', 174, NOW()),
( 'Phara', 174, NOW()),
( 'Quiaca', 174, NOW()),
( 'San Juan del Oro', 174, NOW()),
( 'Yanahuaya', 174, NOW()),
( 'Alto Inambari', 174, NOW()),
( 'San Pedro de Putina Punco', 174, NOW()),
( 'Yunguyo', 175, NOW()),
( 'Anapia', 175, NOW()),
( 'Copani', 175, NOW()),
( 'Cuturapi', 175, NOW()),
( 'Ollaraya', 175, NOW()),
( 'Tinicachi', 175, NOW()),
( 'Unicachi', 175, NOW()),
( 'Moyobamba', 176, NOW()),
( 'Calzada', 176, NOW()),
( 'Habana', 176, NOW()),
( 'Jepelacio', 176, NOW()),
( 'Soritor', 176, NOW()),
( 'Yantalo', 176, NOW()),
( 'Bellavista', 177, NOW()),
( 'Alto Biavo', 177, NOW()),
( 'Bajo Biavo', 177, NOW()),
( 'Huallaga', 177, NOW()),
( 'San Pablo', 177, NOW()),
( 'San Rafael', 177, NOW()),
( 'San José de Sisa', 178, NOW()),
( 'Agua Blanca', 178, NOW()),
( 'San Martín', 178, NOW()),
( 'Santa Rosa', 178, NOW()),
( 'Shatoja', 178, NOW()),
( 'Saposoa', 179, NOW()),
( 'Alto Saposoa', 179, NOW()),
( 'El Eslabón', 179, NOW()),
( 'Piscoyacu', 179, NOW()),
( 'Sacanche', 179, NOW()),
( 'Tingo de Saposoa', 179, NOW()),
( 'Lamas', 180, NOW()),
( 'Alonso de Alvarado', 180, NOW()),
( 'Barranquita', 180, NOW()),
( 'Caynarachi', 180, NOW()),
( 'Cuñumbuqui', 180, NOW()),
( 'Pinto Recodo', 180, NOW()),
( 'Rumisapa', 180, NOW()),
( 'San Roque de Cumbaza', 180, NOW()),
( 'Shanao', 180, NOW()),
( 'Tabalosos', 180, NOW()),
( 'Zapatero', 180, NOW()),
( 'Juanjuí', 181, NOW()),
( 'Campanilla', 181, NOW()),
( 'Huicungo', 181, NOW()),
( 'Pachiza', 181, NOW()),
( 'Pajarillo', 181, NOW()),
( 'Picota', 182, NOW()),
( 'Buenos Aires', 182, NOW()),
( 'Caspisapa', 182, NOW()),
( 'Pilluana', 182, NOW()),
( 'Pucacaca', 182, NOW()),
( 'San Cristóbal', 182, NOW()),
( 'San Hilarión', 182, NOW()),
( 'Shamboyacu', 182, NOW()),
( 'Tingo de Ponasa', 182, NOW()),
( 'Tres Unidos', 182, NOW()),
( 'Rioja', 183, NOW()),
( 'Awajun', 183, NOW()),
( 'Elías Soplin Vargas', 183, NOW()),
( 'Nueva Cajamarca', 183, NOW()),
( 'Pardo Miguel', 183, NOW()),
( 'Posic', 183, NOW()),
( 'San Fernando', 183, NOW()),
( 'Yorongos', 183, NOW()),
( 'Yuracyacu', 183, NOW()),
( 'Tarapoto', 184, NOW()),
( 'Alberto Leveau', 184, NOW()),
( 'Cacatachi', 184, NOW()),
( 'Chazuta', 184, NOW()),
( 'Chipurana', 184, NOW()),
( 'El Porvenir', 184, NOW()),
( 'Huimbayoc', 184, NOW()),
( 'Juan Guerra', 184, NOW()),
( 'La Banda de Shilcayo', 184, NOW()),
( 'Morales', 184, NOW()),
( 'Papaplaya', 184, NOW()),
( 'San Antonio', 184, NOW()),
( 'Sauce', 184, NOW()),
( 'Shapaja', 184, NOW()),
( 'Tocache', 185, NOW()),
( 'Nuevo Progreso', 185, NOW()),
( 'Polvora', 185, NOW()),
( 'Shunte', 185, NOW()),
( 'Uchiza', 185, NOW()),
( 'Tacna', 186, NOW()),
( 'Alto de la Alianza', 186, NOW()),
( 'Calana', 186, NOW()),
( 'Ciudad Nueva', 186, NOW()),
( 'Inclan', 186, NOW()),
( 'Pachia', 186, NOW()),
( 'Palca', 186, NOW()),
( 'Pocollay', 186, NOW()),
( 'Sama', 186, NOW()),
( 'Coronel Gregorio Albarracín Lanchipa', 186, NOW()),
( 'La Yarada los Palos', 186, NOW()),
( 'Candarave', 187, NOW()),
( 'Cairani', 187, NOW()),
( 'Camilaca', 187, NOW()),
( 'Curibaya', 187, NOW()),
( 'Huanuara', 187, NOW()),
( 'Quilahuani', 187, NOW()),
( 'Locumba', 188, NOW()),
( 'Ilabaya', 188, NOW()),
( 'Ite', 188, NOW()),
( 'Tarata', 189, NOW()),
( 'Héroes Albarracín', 189, NOW()),
( 'Estique', 189, NOW()),
( 'Estique-Pampa', 189, NOW()),
( 'Sitajara', 189, NOW()),
( 'Susapaya', 189, NOW()),
( 'Tarucachi', 189, NOW()),
( 'Ticaco', 189, NOW()),
( 'Tumbes', 190, NOW()),
( 'Corrales', 190, NOW()),
( 'La Cruz', 190, NOW()),
( 'Pampas de Hospital', 190, NOW()),
( 'San Jacinto', 190, NOW()),
( 'San Juan de la Virgen', 190, NOW()),
( 'Zorritos', 191, NOW()),
( 'Casitas', 191, NOW()),
( 'Canoas de Punta Sal', 191, NOW()),
( 'Zarumilla', 192, NOW()),
( 'Aguas Verdes', 192, NOW()),
( 'Matapalo', 192, NOW()),
( 'Papayal', 192, NOW()),
( 'Calleria', 193, NOW()),
( 'Campoverde', 193, NOW()),
( 'Iparia', 193, NOW()),
( 'Masisea', 193, NOW()),
( 'Yarinacocha', 193, NOW()),
( 'Nueva Requena', 193, NOW()),
( 'Manantay', 193, NOW()),
( 'Raymondi', 194, NOW()),
( 'Sepahua', 194, NOW()),
( 'Tahuania', 194, NOW()),
( 'Yurua', 194, NOW()),
( 'Padre Abad', 195, NOW()),
( 'Irazola', 195, NOW()),
( 'Curimana', 195, NOW()),
( 'Neshuya', 195, NOW()),
( 'Alexander Von Humboldt', 195, NOW()),
( 'Neshuya', 195, NOW()),
( 'Alexander Von Humboldt', 195, NOW()),
( 'Purus', 196, NOW());
