INSERT INTO public."PeruRegion" (name,"updatedAt") VALUES
('Amazonas',NOW()),
('Áncash',NOW()),
('Apurímac',NOW()),
('Arequipa',NOW()),
('Ayacucho',NOW()),
('Cajamarca',NOW()),
('Callao',NOW()),
('Cusco',NOW()),
('Huancavelica', NOW()),
('Huánuco', NOW()),
('Ica', NOW()),
('Junín', NOW()),
('La Libertad', NOW()),
('Lambayeque', NOW()),
('Lima', NOW()),
('Loreto', NOW()),
('Madre de Dios', NOW()),
('Moquegua', NOW()),
('Pasco', NOW()),
('Piura', NOW()),
('Puno', NOW()),
('San Martín', NOW()),
('Tacna', NOW()),
('Tumbes', NOW()),
('Ucayali', NOW());